### ISSUE TITLE
poca-subscribe add fails for some podcasts

### ISSUE THREAD

**Issue by rohshall** [brokkr/poca#112]
`
poca-subscribe add
Url of subscription: http://cbsradionewsfeed.com/rss.php?id=126&ud=12

Traceback (most recent call last):
  File "/usr/local/bin/poca-subscribe", line 40, in <module>
    main()
  File "/usr/local/bin/poca-subscribe", line 26, in main
    sub_dic, sub_category = poca.subscribe.user_input_add_sub()
  File "/usr/local/lib/python3.6/site-packages/poca/subscribe.py", line 118, in user_input_add_sub
    url_stats.print_stats()
  File "/usr/local/lib/python3.6/site-packages/poca/feedstats.py", line 40, in print_stats
    self.set_lhs()
  File "/usr/local/lib/python3.6/site-packages/poca/feedstats.py", line 59, in set_lhs
    lhs['avg_mb'] = self.get_avg_size()
  File "/usr/local/lib/python3.6/site-packages/poca/feedstats.py", line 80, in get_avg_size
    lengths = [int(x) for x in lengths if int(x) > 0]
  File "/usr/local/lib/python3.6/site-packages/poca/feedstats.py", line 80, in <listcomp>
    lengths = [int(x) for x in lengths if int(x) > 0]
ValueError: invalid literal for int() with base 10: ''

`

**Comment by brokkr** [comment]
Thanks for letting me know. Back from a holiday break, will take a closer look shortly.
