### ISSUE TITLE
poca-subscribe

### ISSUE THREAD

**Issue by brokkr** [brokkr/poca#121]
```
[ SERVIAN ~ ] poca-subscribe add
Url of subscription: https://hey-lesson.castos.com/feed

Traceback (most recent call last):
  File "/usr/bin/poca-subscribe", line 40, in <module>
    main()
  File "/usr/bin/poca-subscribe", line 26, in main
    sub_dic, sub_category = poca.subscribe.user_input_add_sub()
  File "/usr/lib/python3.8/site-packages/poca/subscribe.py", line 118, in user_input_add_sub
    url_stats.print_stats()
  File "/usr/lib/python3.8/site-packages/poca/feedstats.py", line 40, in print_stats
    self.set_lhs()
  File "/usr/lib/python3.8/site-packages/poca/feedstats.py", line 59, in set_lhs
    lhs['avg_mb'] = self.get_avg_size()
  File "/usr/lib/python3.8/site-packages/poca/feedstats.py", line 80, in get_avg_size
    lengths = [int(x) for x in lengths if int(x) > 0]
  File "/usr/lib/python3.8/site-packages/poca/feedstats.py", line 80, in <listcomp>
    lengths = [int(x) for x in lengths if int(x) > 0]
ValueError: invalid literal for int() with base 10: '00:42:30'

```

**Comment by brokkr** [comment]
Can't replicate. maybe just a bug in the feed at the time?
