### ISSUE TITLE
Permissions: New file permissions fail poca-subscribe add

### ISSUE THREAD

**Issue by brokkr** [brokkr/poca#127]
Running poca-subscribe add fails with a PermissionError because of new less overreachy permissions check.

**Comment by brokkr** [comment]
Also just running poca when the feed 301s:

```
Traceback (most recent call last):
  File "/home/mads/.virtualenvs/poca11/bin/poca", line 85, in <module>
    main()
  File "/home/mads/.virtualenvs/poca11/bin/poca", line 57, in main
    _outcome = poca.subscribe.update_url(args, subdata)
  File "/home/mads/.virtualenvs/poca11/lib/python3.8/site-packages/poca/subscribe.py", line 194, in update_url
    _outcome = write(conf)
  File "/home/mads/.virtualenvs/poca11/lib/python3.8/site-packages/poca/subscribe.py", line 42, in write
    with open(conf.paths.config_file, 'r+') as f:
PermissionError: [Errno 13] Permission denied: '/home/mads/.virtualenvs/poca11/.poca/poca.xml'
```

**Comment by brokkr** [comment]
Feed: http://crateandcrowbar.com/feed/podcast/
Redirects to: http://crateandcrowbar.com/category/episode/feed/

**Comment by brokkr** [comment]
And here's poca-subscribe failing:

```
rl of subscription: https://feeds.twit.tv/podcasts/sn.xml

Author: Leo Laporte (distro@twit.tv)                        PUBLISHED / 5 WEEKS
Title:  Security Now (Audio)                                                   
                                                                  ▮            
Last episode: SN 819: The WiFi Frag Attacks - DarkSide Fol        ▮            
Published:    19 May 2021                                         ▮            
                                                                  ▮            
Avg. size of episode:   57 Mb                                     ▮            
Avg. length of episode: 2h 3m                               M  T  W  T  F  S  S

Title of subscription: (Enter to use feed title) 
Maximum number of files in subscription: (integer/Enter to skip) 3
Get earliest entries first: (yes/no/Enter to skip) 
Category for subscription: 
To add metadata, rename or filters settings, please edit poca.xml
Traceback (most recent call last):
  File "/home/mads/.virtualenvs/poca11/bin/poca-subscribe", line 40, in <module>
    main()
  File "/home/mads/.virtualenvs/poca11/bin/poca-subscribe", line 27, in main
    poca.subscribe.add_sub(conf, sub_category, sub_dic)
  File "/home/mads/.virtualenvs/poca11/lib/python3.8/site-packages/poca/subscribe.py", line 145, in add_sub
    write(conf)
  File "/home/mads/.virtualenvs/poca11/lib/python3.8/site-packages/poca/subscribe.py", line 42, in write
    with open(conf.paths.config_file, 'r+') as f:
PermissionError: [Errno 13] Permission denied: '/home/mads/.virtualenvs/poca11/.poca/poca.xml'
```

**Comment by brokkr** [comment]
Should be fixed for both cases. User is told of feed move (in case of 301) _and_ of failure to update config file. Suggestion to either fix permissions or update the feed url manually.
