### ISSUE TITLE
Tagging failures are ignored

### ISSUE THREAD

**Issue by brokkr** [brokkr/poca#73]
We silently pass by any failures when attempting tagging. Can we try to convey some of the issues to the user?

**Comment by brokkr** [comment]
From September 8th:

```
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/poco/subupgrade.py", line 26, in run
    sub_upgrade = self.target(self.subdata)
  File "/usr/local/lib/python3.5/dist-packages/poco/subupgrade.py", line 60, in __init__
    outcome = self.acquire(uid, entry, subdata)
  File "/usr/local/lib/python3.5/dist-packages/poco/subupgrade.py", line 90, in acquire
    subdata.sub, subdata.jar, entry)
  File "/usr/local/lib/python3.5/dist-packages/poco/tag.py", line 25, in tag_audio_file
    audio = mutagen.File(entry['poca_abspath'])
  File "/usr/local/lib/python3.5/dist-packages/mutagen/_util.py", line 137, in wrapper_func
    return func(h, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mutagen/_file.py", line 297, in File
    return Kind(fileobj, filename=filething.filename)
  File "/usr/local/lib/python3.5/dist-packages/mutagen/_file.py", line 49, in __init__
    self.load(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mutagen/_util.py", line 129, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mutagen/id3/_file.py", line 406, in load
    self.info = self._Info(fileobj, offset)
  File "/usr/local/lib/python3.5/dist-packages/mutagen/_util.py", line 158, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mutagen/mp3/__init__.py", line 396, in __init__
    raise HeaderNotFoundError("can't sync to MPEG frame")
mutagen.mp3.HeaderNotFoundError: can't sync to MPEG frame
```

I can see no way to relate it to one specific file, sadly.

**Comment by brokkr** [comment]
As part of the overhaul of errors related to history tagging failures have been classified as non-fatal failures. These are reported as they happen in verbose mode and after the fact in non-verbose mode. In neither case are they cosndiered fatal.

It remains to be seen if we need to look more specifically for them (see above) or spot any missing.

**Comment by brokkr** [comment]
We still need to go through and test tagging issues. As of now the only type we've identified is if mutagen cannot see the file as an audio file. What about bad id3 tags, encodings etc.?
