### ISSUE TITLE
NameError: name 'msg' is not defined

### ISSUE THREAD

**Issue by georf** [brokkr/poca#94]
If I starting poca without `--config` path I get the following error:

```
$ poca-subscribe list
Traceback (most recent call last):
  File "/usr/local/bin/poca-subscribe", line 43, in <module>
    main()
  File "/usr/local/bin/poca-subscribe", line 22, in main
    conf = poco.config.Config(args, merge_default=False)
  File "/usr/local/lib/python3.4/dist-packages/poco/config.py", line 68, in __init__
    self.paths = Paths(args)
  File "/usr/local/lib/python3.4/dist-packages/poco/config.py", line 103, in __init__
    self.test_paths()
  File "/usr/local/lib/python3.4/dist-packages/poco/config.py", line 116, in test_paths
    output.config_fatal(msg)
NameError: name 'msg' is not defined
```

**Comment by brokkr** [comment]
Thanks! I must have moved some stuff into a function and not updated. That's what you get for turning your linter off. Fixed.
