### ISSUE TITLE
TypeError: Tuple or struct_time argument required

### ISSUE THREAD

**Issue by georf** [brokkr/poca#95]
Hello again,

I tried to add some of my favorite podcasts and got this error: 
```
$ poca-subscribe --config /media/freigabe-ohne-backup/samba/podcasts/ add
Press enter to skip setting (except * mandatory)
* Url of subscription? http://www.ard.de/static/radio/radiofeature/rss/podcast.xml

Traceback (most recent call last):
  File "/usr/local/bin/poca-subscribe", line 43, in <module>
    main()
  File "/usr/local/bin/poca-subscribe", line 26, in main
    sub_dic, sub_category = poco.subscribe.user_input_add_sub()
  File "/usr/local/lib/python3.4/dist-packages/poco/subscribe.py", line 120, in user_input_add_sub
    url_stats = Feedstats(sub_dic['url'])
  File "/usr/local/lib/python3.4/dist-packages/poco/feedstats.py", line 26, in __init__
    self.entries = [x for x in self.doc.entries if \
  File "/usr/local/lib/python3.4/dist-packages/poco/feedstats.py", line 27, in <listcomp>
    age(x['published_parsed']) < 35]
  File "/usr/local/lib/python3.4/dist-packages/poco/feedstats.py", line 25, in <lambda>
    age = lambda x: (time.mktime(now) - time.mktime(x)) / (24*3600)
TypeError: Tuple or struct_time argument required
```

**Comment by brokkr** [comment]
Well spotted. Apparently  they forgot to put a date on the the most recent episode which I presumed all episodes had. Fixing it.
